<a href="https://colab.research.google.com/github/calle-sa/Programaci-n_con_LLMs/blob/main/content/LAB%2001.01%20-%20PRACTICE%20SUBMISSION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# LAB 01.01 - Practice submission

<a target="_blank" href="https://colab.research.google.com/github/rramosp/ai4eng.v1/blob/main/content/LAB%2001.01%20-%20PRACTICE%20SUBMISSION.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
    

In [1]:
!wget --no-cache -O init.py -q https://raw.githubusercontent.com/rramosp/ai4eng.v1/main/content/init.py
import init; init.init(force_download=False); init.get_weblink()


replicating local resources


In [11]:
import inspect
from local.lib.rlxmoocapi import session
session.LoginSequence(endpoint=init.endpoint, course_id=init.course_id, lab_id="L01.01", varname="student");

logging in as santiago.callea@udea.edu.co... please wait

-------------
using course session ai4eng.v1.udea.r4::2026.1
success!! you are logged in
-------------


### Ejercicio 1: Suma dos matrices

Completa la función `suma_matrices` para que, dadas dos arrays numpy cualquiera devuelva la suma elemento a elemento.

#### Ejemplo de ejecución

    > s = np.array([1,2,3])
    > t = np.array([4,5,6])
    > suma_matrices(s,t)
    
      [5 7 9]
     
_Sugerencia_: completa el código de la siguiente manera:

    def suma_matrices(a,b):
       ## --- TU CODIGO AQUI ---
       result = a + b
       return result

In [13]:

def suma_matrices(a,b):
    result = a + b
    return result



comprueba manualmente tu código

In [14]:
import numpy as np
a = np.random.randint(10, size=(3,2))
b = np.random.randint(10, size=(3,2))
print (a)
print (b)
print (suma_matrices(a,b))

[[4 2]
 [5 2]
 [6 8]]
[[4 4]
 [2 6]
 [5 0]]
[[ 8  6]
 [ 7  8]
 [11  8]]


#### registra tu solución en línea

In [15]:
student.submit_task(globals(), task_id="task_01");

### Ejercicio 2: Realiza un cálculo

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

En este ejercicio, al ejecutar la celda de más abajo, se generará una lista de número aleatorios.

Tendrás que calcular el valor promedio de la lista y asignarlo a la variable `avg` más abajo.

Puedes usar el método que quieras para realizar el cálculo (a mano, excel, python, etc.) lo que importa es el valor que obtengas.


In [16]:
import numpy as np
rlist = np.random.randint(100, size=10)
rlist

array([ 7, 55,  3, 31, 67, 86, 30, 68, 48,  0])

#### tu solución

In [17]:
avg = np.mean(rlist)
avg

np.float64(39.5)

#### registra tu solución en línea

In [18]:
student.submit_task(globals(), task_id="task_02");